### ISSUE TITLE
fix: "Available balance" is gone from swap UI, add back

### ISSUE THREAD

**Issue by JULl4N** [ZigZagExchange/mammoth_UI#53]
Old
![Screenshot 2022-06-11 at 08 12 09](https://user-images.githubusercontent.com/103177338/173175735-dc9de61c-58ef-41d5-addd-90b450cba5d6.png)

New
![Screenshot 2022-06-11 at 08 12 12](https://user-images.githubusercontent.com/103177338/173175745-7e7bd9c7-f5f9-4fb7-93ae-d60cca022e71.png)

**Comment by 0xtrooper** [comment]
fixed with #70
