### ISSUE TITLE
`To` token amount responds very slowly and wrongly

### ISSUE THREAD

**Issue by JULl4N** [ZigZagExchange/mammoth_UI#89]
Try an input and the `to` amount takes super long to load/change and sometimes it stays stuck on the wrong amount

<img width="589" alt="Screenshot 2022-07-22 at 13 41 26" src="https://user-images.githubusercontent.com/103177338/180432492-b29806bb-2fea-4c6e-9163-b3dec0c4713e.png">

https://gyazo.com/e947ee4c4d7e4c2afea0ca6b6f4c7d04

**Comment by 0xtrooper** [comment]
slow cant be fixed - thats starknet.

rest is fixed by #93
